### ISSUE TITLE
Add examples with Graphviz

### ISSUE THREAD

**Issue by vdjagilev** [vdjagilev/nmap-formatter#116]
* Usage page changes
* Screenshots on examples page
* Move screenshots on top, add graphviz example

**Comment by zejjnt** [comment]
This needs to be opened again, there are no examples for Graphviz to make it like the image on the landing page.
This
![image](https://github.com/vdjagilev/nmap-formatter/assets/20284369/f606c60d-6740-402b-a925-966c11b6d3cb)
is not even close. I do _not_ intend for the following to sound insulting and such (I am a staunch proponent of Linux and FOSS in general), but the extremely vague and simple examples given - except for HTML which actually does result in the exact layout from the screenshot without additional CLI arguments - are close to useless.
Instead, they serve as a textbook example of why a newcomer to the platform feels that the ecosystem is "intimidating" and "not ready for the desktop" because they have to figure everything out by themselves to accomplish what is said to be possible.

So please, elaborate the examples *a lot*.
This tool and the potential outputs of it are really appealing to me, but I shouldn't need to learn the entire graphviz library in order to get the kind of graph given as the example.

I absolutely appreciate the work you have put into making this tool, but in the current form it is simply not user-friendly. And I am writing this with the best of intentions, because as of now my takeaway is that there is a huge potential here and it is going to waste.

**Comment by vdjagilev** [comment]
@zejjnt hi :wave: 
I see. Graphviz example was taken from this XML https://github.com/nmap/nmap/blob/master/zenmap/radialnet/share/sample/nmap_example.xml

It has a lot of endpoints scanned at once (you can see in the xml `<nmaprun scanner="nmap" args="nmap -A -v -oX sample-03.xml freshmeat.net sourceforge.net nmap.org kernel.org openbsd.org netbsd.org google.com gmail.com ..."`), in your case you have scanned only one domain, therefore the image is not as impressive. 

These little dots represent hops. It's basically intermediary routers that packet goes through, sometimes packets go through other places, so it can be shown in the graph in the end.

Since there is quite big amount of options it's a bit hard to compress it into 1 readme file, so there [Wiki](https://github.com/vdjagilev/nmap-formatter/wiki/Usage) for that, there is section `Flags and Output Options` that can help you to tweak it however you want to. However, there is not much options for Graphviz
